services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gpu_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/database/schemas:/docker-entrypoint-initdb.d

volumes:
  postgres_data: